//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIS_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UisContext : DbContext
    {
        public UisContext()
            : base("name=UisContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccountOfficeAuth> AccountOfficeAuths { get; set; }
        public DbSet<adminStatu> adminStatus { get; set; }
        public DbSet<chat> chats { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<cse_courseLayout> cse_courseLayout { get; set; }
        public DbSet<DeanApprovedEntry> DeanApprovedEntries { get; set; }
        public DbSet<DeanOfficeAuth> DeanOfficeAuths { get; set; }
        public DbSet<enrolledStudent> enrolledStudents { get; set; }
        public DbSet<enrollmentStatu> enrollmentStatus { get; set; }
        public DbSet<FiEnrolledStudent> FiEnrolledStudents { get; set; }
        public DbSet<FiSemesterFee> FiSemesterFees { get; set; }
        public DbSet<HallFee> HallFees { get; set; }
        public DbSet<HallProvostAuth> HallProvostAuths { get; set; }
        public DbSet<HallTransaction> HallTransactions { get; set; }
        public DbSet<MailAuth> MailAuths { get; set; }
        public DbSet<NoticeBoard> NoticeBoards { get; set; }
        public DbSet<Post> Posts { get; set; }
        public DbSet<SemesterFee> SemesterFees { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<TempBank> TempBanks { get; set; }
    }
}
