//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIS_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string UserName { get; set; }
        public string DateTime { get; set; }
        public string Body { get; set; }
        public string Image { get; set; }
        public string UserId { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Student Student { get; set; }
    }
}
