//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdmissionContext : DbContext
    {
        public AdmissionContext()
            : base("name=AdmissionContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<a_alloted> a_alloted { get; set; }
        public virtual DbSet<a_choice> a_choice { get; set; }
        public virtual DbSet<allotCount> allotCounts { get; set; }
        public virtual DbSet<b_alloted> b_alloted { get; set; }
        public virtual DbSet<b_choice> b_choice { get; set; }
        public virtual DbSet<check_eligible> check_eligible { get; set; }
        public virtual DbSet<studentDb> studentDbs { get; set; }
        public virtual DbSet<c_alloted> c_alloted { get; set; }
        public virtual DbSet<c_choice> c_choice { get; set; }
    }
}
