//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_alloted
    {
        public int id { get; set; }
        public string studentId { get; set; }
        public string allotedFaculty { get; set; }
        public string allotedHall { get; set; }
        public string status { get; set; }
    
        public virtual c_choice c_choice { get; set; }
        public virtual studentDb studentDb { get; set; }
    }
}
