//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat
    {
        public int id { get; set; }
        public string userName { get; set; }
        public string message { get; set; }
        public string timeDate { get; set; }
        public string selectionCode { get; set; }
    }
}
