//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cse_courseLayout
    {
        public int ID { get; set; }
        public string courseCode { get; set; }
        public string courseTitle { get; set; }
        public Nullable<double> creditHour { get; set; }
        public string forSemester { get; set; }
    }
}
