//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoticeBoard
    {
        public int NoticeId { get; set; }
        public string Topic { get; set; }
        public string DateTime { get; set; }
        public string NoticeTitle { get; set; }
        public string NoticeBody { get; set; }
        public string Photo { get; set; }
    }
}
