//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentDb
    {
        public studentDb()
        {
            this.a_alloted = new HashSet<a_alloted>();
        }
    
        public string studentRoll { get; set; }
        public string unit { get; set; }
        public string name { get; set; }
        public string sex { get; set; }
        public string father { get; set; }
        public string hsc_roll { get; set; }
        public string ssc_roll { get; set; }
        public string hsc_reg { get; set; }
        public string ssc_reg { get; set; }
        public string photoLink { get; set; }
    
        public virtual ICollection<a_alloted> a_alloted { get; set; }
        public virtual b_alloted b_alloted { get; set; }
        public virtual c_alloted c_alloted { get; set; }
    }
}
